services:
  teipublisher:
    image: unillett/existdb-tei-publisher:${DOCKER_IMAGE_TAG}
    build:
        context: .
    volumes:
      - exist-data:/exist/data
      - ./autodeploy:/src/autodeploy
    ports:
      - "127.0.0.1:${DOCKER_HOST_PORT}:8080"
    environment:
      - TEIPUBLISHER_CONTEXT_PATH=${TEIPUBLISHER_CONTEXT_PATH-auto}
    container_name: ${DOCKER_CONTAINER_NAME}

volumes:
  exist-data:
    name: ${DOCKER_VOLUME_NAME}
