name: docker-prod
on:
  push:
    branches:
      - 'main'
permissions: read-all

env:
  # From https://hub.docker.com/r/duncdrum/existdb/tags
  EXISTDB_VERSION: 6.4.0-debug-slim
  TEMPLATING_VERSION: 1.2.1
  PUBLISHER_LIB_VERSION: 4.0.4
  ROUTER_VERSION: 1.11.0

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux/amd64
          - os: ubuntu-26.04-arm
            arch: linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Build image
        uses: unil-lettres/actions/docker-build@main
        with:
          dockerfile: ./Dockerfile
          target: existdb
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: existdb
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          build_args: |
            EXISTDB_VERSION=${{ env.EXISTDB_VERSION }}
            TEMPLATING_VERSION=${{ env.TEMPLATING_VERSION }}
            PUBLISHER_LIB_VERSION=${{ env.PUBLISHER_LIB_VERSION }}
            ROUTER_VERSION=${{ env.ROUTER_VERSION }}

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Merge digests
        uses: unil-lettres/actions/docker-merge@main
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          tag: latest
          additional_tag: ${{ env.EXISTDB_VERSION }}-core${{ env.PUBLISHER_LIB_VERSION }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge]
    if: success()
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Update description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
